// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7kvsPxI3zhCHKyQdD8cnQc_eMUzKwfw',
    appId: '1:995149379469:android:d61b10b7645e39cefaefc4',
    messagingSenderId: '995149379469',
    projectId: 'ecommerce-1269a',
    storageBucket: 'ecommerce-1269a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuprHb2Eat5CQZumoJeYQFGPG2yP9wfA',
    appId: '1:995149379469:ios:ef0e055844635ea3faefc4',
    messagingSenderId: '995149379469',
    projectId: 'ecommerce-1269a',
    storageBucket: 'ecommerce-1269a.firebasestorage.app',
    androidClientId: '995149379469-u0frkean9nmbn7ikmdfl165aq8rav4ts.apps.googleusercontent.com',
    iosClientId: '995149379469-p7r4qgisdlrc91h6cb57abso7nu0v7st.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoTaskManager',
  );

}